server:
  port: 8989
  address: 172.31.4.120 #EC2 private IP
# project 별칭 등록
# 다른 project에서 호출할때 사용되는 이름
spring:
  application:
    name: CONSUMER-SERVICE
  boot:
    admin:
      client:
        instance:
          service-url: http://54.180.138.74:8989 #EC2 public IP
management:
  endpoints:
    web:
      exposure: 
        include: "*"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://43.202.50.68:8761/eureka/ #Eureka EC2 public IP
  instance:
    prefer-ip-address: true
    ip-address: ${server.address}
    instance-id: ${server.address}:${spring.application.name}:${server.port}





